name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3.0.2
    - uses: volta-cli/action@v4
    - run: npm ci
    - run: npm run lint:js

  build:
    name: "Node ${{ matrix.node-version }}"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3.0.2
    - uses: volta-cli/action@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: install dependencies
      run: npm ci
    - run: npm run test:vitest

  release-it-compat:
    name: "release-it@${{ matrix.release-it-version }}"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        release-it-version: ["14.0.0", "14.1.0", "14.2.0", "15.1.3", "^15.0.0", "^16.0.0"]

    steps:
    - uses: actions/checkout@v3.0.2
    - uses: volta-cli/action@v4
    - name: install dependencies
      run: npm ci
    - run: npm install --saveDev release-it@${{ matrix.release-it-version }}
    - run: npm run test:vitest
